# Generated by Django 2.1.5 on 2019-03-17 04:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import web.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z_]*$', 'IDは英数字もしくはアンダースコア(_)のみとしてください')], verbose_name='お客様No')),
                ('company_name', models.CharField(max_length=50, verbose_name='会社名')),
                ('dept_name', models.CharField(max_length=50, verbose_name='部署名')),
                ('representative', models.CharField(max_length=50, verbose_name='担当者名')),
                ('zip', models.CharField(max_length=10, validators=[web.models.validate_postcode], verbose_name='送付先郵便番号')),
                ('address', models.CharField(max_length=100, verbose_name='請求書送付先住所')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='メールアドレス')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, validators=[web.models.validate_phonenumber], verbose_name='電話番号')),
            ],
            options={
                'verbose_name': '顧客',
                'verbose_name_plural': '顧客',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='出力日')),
                ('file', models.FileField(upload_to='', verbose_name='請求書ファイル')),
            ],
            options={
                'verbose_name': '請求明細',
                'verbose_name_plural': '請求明細',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='注文ID')),
                ('amount', models.IntegerField(verbose_name='数量')),
                ('month_used', models.CharField(max_length=6, validators=[web.models.validate_month], verbose_name='ご利用月')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Customer', verbose_name='顧客')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.Invoice', verbose_name='請求')),
            ],
            options={
                'verbose_name': '注文',
                'verbose_name_plural': '注文',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z_]*$', 'IDは英数字もしくはアンダースコア(_)のみとしてください')], verbose_name='商品コード')),
                ('name', models.CharField(max_length=100, verbose_name='商品・サービス名')),
                ('price', models.IntegerField(verbose_name='単価')),
                ('tax_type', models.CharField(choices=[('課税', '課税'), ('非課税', '非課税')], max_length=10, verbose_name='税区分')),
            ],
            options={
                'verbose_name': '商材',
                'verbose_name_plural': '商材',
            },
        ),
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField(blank=True, verbose_name='税率')),
                ('valid_from', models.DateField(verbose_name='有効開始日')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name='有効終了日')),
            ],
            options={
                'verbose_name': '税率',
                'verbose_name_plural': '税率',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Product', verbose_name='商品'),
        ),
        migrations.AddField(
            model_name='order',
            name='tax_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.TaxRate', verbose_name='税率'),
        ),
    ]
