# Generated by Django 2.1.5 on 2019-03-14 00:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import web.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z_]*$', 'IDは英数字もしくはアンダースコア(_)のみとしてください')], verbose_name='お客様No')),
                ('company_name', models.CharField(max_length=50, verbose_name='会社名')),
                ('dept_name', models.CharField(max_length=50, verbose_name='部署名')),
                ('representative', models.CharField(max_length=50, verbose_name='担当者名')),
                ('zip', models.CharField(max_length=10, validators=[web.models.validate_postcode], verbose_name='送付先郵便番号')),
                ('address', models.CharField(max_length=100, verbose_name='請求書送付先住所')),
                ('phone', models.CharField(max_length=20, validators=[web.models.validate_phonenumber], verbose_name='電話番号')),
            ],
            options={
                'verbose_name': '顧客',
                'verbose_name_plural': '顧客',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_used', models.CharField(max_length=6, validators=[web.models.validate_month], verbose_name='ご利用月')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Customer', verbose_name='顧客')),
            ],
            options={
                'verbose_name': '請求明細',
                'verbose_name_plural': '請求明細',
            },
        ),
    ]
