# Generated by Django 2.1.5 on 2019-03-14 04:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z_]*$', 'IDは英数字もしくはアンダースコア(_)のみとしてください')], verbose_name='商品コード')),
                ('name', models.CharField(max_length=100, verbose_name='商品・サービス名')),
                ('price', models.IntegerField(verbose_name='単価')),
                ('tax_type', models.CharField(choices=[('課税', '課税'), ('非課税', '非課税')], max_length=10, verbose_name='税区分')),
            ],
            options={
                'verbose_name': '商材',
                'verbose_name_plural': '商材',
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='メールアドレス'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='amount',
            field=models.IntegerField(default=1, verbose_name='数量'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='code',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z_]*$', 'IDは英数字もしくはアンダースコア(_)のみとしてください')], verbose_name='お客様No'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[web.models.validate_phonenumber], verbose_name='電話番号'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.Product', verbose_name='商品'),
            preserve_default=False,
        ),
    ]
