# Generated by Django 2.1.5 on 2019-03-17 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='tax_rate',
        ),
    ]
