# Generated by Django 2.1.5 on 2019-07-16 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceentity',
            name='invoice_closed_at',
            field=models.CharField(choices=[('末日', '末日'), ('20日', '20日')], default=1, max_length=100, verbose_name='締め日'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoiceentity',
            name='payment_due_to',
            field=models.CharField(choices=[('翌月末', '翌月末'), ('翌々月末', '翌々月末')], max_length=100, verbose_name='支払い期日'),
        ),
    ]
