# Generated by Django 2.1.5 on 2019-05-21 05:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='invoice_code',
        ),
        migrations.AddField(
            model_name='invoice',
            name='id',
            field=models.CharField(default=1, max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='会社ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='corporate_number',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z_]*$', 'IDは英数字もしくはアンダースコア(_)のみとしてください')], verbose_name='法人番号'),
        ),
        migrations.AlterField(
            model_name='invoicedetail',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='会社ID'),
        ),
        migrations.AlterField(
            model_name='invoiceentity',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='会社ID'),
        ),
    ]
