# Generated by Django 2.1.5 on 2019-05-20 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip', models.CharField(max_length=100, verbose_name='郵便番号')),
                ('address_1', models.CharField(max_length=100, verbose_name='住所1')),
                ('address_2', models.CharField(max_length=100, verbose_name='住所2')),
                ('phone', models.CharField(max_length=100, verbose_name='電話番号')),
            ],
        ),
        migrations.AlterField(
            model_name='invoicedetail',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='details', to='web.Invoice', verbose_name='請求書'),
        ),
    ]
