# Generated by Django 2.1 on 2019-05-30 04:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handwritteninvoice',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2019, 5, 30, 4, 53, 27, 144342, tzinfo=utc), verbose_name='作成日'),
        ),
    ]
