# Generated by Django 2.1.5 on 2019-03-17 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_remove_order_tax_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='code',
            field=models.CharField(default=1, max_length=100, unique=True, verbose_name='請求書番号'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.Customer', verbose_name='顧客'),
            preserve_default=False,
        ),
    ]
