# Generated by Django 2.1.5 on 2019-05-23 03:46

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20190521_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='HandWrittenInvoice',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('customer_id', models.CharField(max_length=50, verbose_name='お客様番号')),
                ('vision_phone_number', models.CharField(max_length=50, verbose_name='連絡先電話番号')),
                ('zip', models.CharField(max_length=10, validators=[web.models.validate_postcode], verbose_name='請求郵便番号')),
                ('address_1', models.CharField(choices=[('東京都', '東京都'), ('北海道', '北海道'), ('秋田県', '秋田県')], max_length=10, verbose_name='住所1')),
                ('address_2', models.CharField(max_length=30, verbose_name='住所2')),
                ('company_name', models.CharField(max_length=100, verbose_name='請求会社名')),
                ('dept', models.CharField(max_length=100, verbose_name='請求部署')),
                ('person', models.CharField(max_length=50, verbose_name='請求宛名')),
                ('project_1', models.CharField(blank=True, max_length=50, null=True, verbose_name='請求宛名1')),
                ('date_created', models.DateField(default=datetime.datetime(2019, 5, 23, 3, 46, 30, 43421, tzinfo=utc), verbose_name='作成日')),
                ('invoice_price', models.IntegerField(verbose_name='請求金額')),
                ('due_date', models.DateField(verbose_name='支払期日')),
            ],
        ),
        migrations.CreateModel(
            name='HandWrittenInvoiceDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_no', models.IntegerField(verbose_name='行番号')),
                ('yearmonth', models.CharField(blank=True, max_length=6, null=True)),
                ('product_category', models.CharField(blank=True, max_length=100, null=True)),
                ('product_name', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('unit_price', models.IntegerField(blank=True, null=True)),
                ('tax_type', models.CharField(blank=True, choices=[('1', '課税'), ('2', '非課税')], max_length=10, null=True)),
                ('total_wo_tax', models.IntegerField(blank=True, null=True)),
                ('tax_price', models.IntegerField(blank=True, null=True)),
                ('total_w_tax', models.IntegerField(blank=True, null=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='web.HandWrittenInvoice')),
            ],
        ),
    ]
