# Generated by Django 2.1.5 on 2019-03-15 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_invoice_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='subtotal',
            field=models.IntegerField(default=0, verbose_name='小計'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tax',
            field=models.IntegerField(default=0, verbose_name='税'),
        ),
    ]
