# Generated by Django 2.1.5 on 2019-03-17 08:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20190317_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(default=datetime.date(2019, 3, 31), verbose_name='振込期限'),
        ),
    ]
