# Generated by Django 2.1.5 on 2019-06-03 01:23

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20190530_2155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='invoice_printed_at',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='pdf',
        ),
        migrations.AlterField(
            model_name='company',
            name='address_pref',
            field=models.CharField(choices=[('北海道', '北海道'), ('青森県', '青森県'), ('岩手県', '岩手県'), ('宮城県', '宮城県'), ('秋田県', '秋田県'), ('山形県', '山形県'), ('福島県', '福島県'), ('茨城県', '茨城県'), ('栃木県', '栃木県'), ('群馬県', '群馬県'), ('埼玉県', '埼玉県'), ('千葉県', '千葉県'), ('東京都', '東京都'), ('神奈川県', '神奈川県'), ('新潟県', '新潟県'), ('富山県', '富山県'), ('石川県', '石川県'), ('福井県', '福井県'), ('山梨県', '山梨県'), ('長野県', '長野県'), ('岐阜県', '岐阜県'), ('静岡県', '静岡県'), ('愛知県', '愛知県'), ('三重県', '三重県'), ('滋賀県', '滋賀県'), ('京都府', '京都府'), ('大阪府', '大阪府'), ('兵庫県', '兵庫県'), ('奈良県', '奈良県'), ('和歌山県', '和歌山県'), ('鳥取県', '鳥取県'), ('島根県', '島根県'), ('岡山県', '岡山県'), ('広島県', '広島県'), ('山口県', '山口県'), ('徳島県', '徳島県'), ('香川県', '香川県'), ('愛媛県', '愛媛県'), ('高知県', '高知県'), ('福岡県', '福岡県'), ('佐賀県', '佐賀県'), ('長崎県', '長崎県'), ('熊本県', '熊本県'), ('大分県', '大分県'), ('宮崎県', '宮崎県'), ('鹿児島県', '鹿児島県'), ('沖縄県', '沖縄県')], max_length=10, verbose_name='契約者都道府県'),
        ),
        migrations.AlterField(
            model_name='handwritteninvoice',
            name='address_1',
            field=models.CharField(choices=[('北海道', '北海道'), ('青森県', '青森県'), ('岩手県', '岩手県'), ('宮城県', '宮城県'), ('秋田県', '秋田県'), ('山形県', '山形県'), ('福島県', '福島県'), ('茨城県', '茨城県'), ('栃木県', '栃木県'), ('群馬県', '群馬県'), ('埼玉県', '埼玉県'), ('千葉県', '千葉県'), ('東京都', '東京都'), ('神奈川県', '神奈川県'), ('新潟県', '新潟県'), ('富山県', '富山県'), ('石川県', '石川県'), ('福井県', '福井県'), ('山梨県', '山梨県'), ('長野県', '長野県'), ('岐阜県', '岐阜県'), ('静岡県', '静岡県'), ('愛知県', '愛知県'), ('三重県', '三重県'), ('滋賀県', '滋賀県'), ('京都府', '京都府'), ('大阪府', '大阪府'), ('兵庫県', '兵庫県'), ('奈良県', '奈良県'), ('和歌山県', '和歌山県'), ('鳥取県', '鳥取県'), ('島根県', '島根県'), ('岡山県', '岡山県'), ('広島県', '広島県'), ('山口県', '山口県'), ('徳島県', '徳島県'), ('香川県', '香川県'), ('愛媛県', '愛媛県'), ('高知県', '高知県'), ('福岡県', '福岡県'), ('佐賀県', '佐賀県'), ('長崎県', '長崎県'), ('熊本県', '熊本県'), ('大分県', '大分県'), ('宮崎県', '宮崎県'), ('鹿児島県', '鹿児島県'), ('沖縄県', '沖縄県')], max_length=10, verbose_name='住所1'),
        ),
        migrations.AlterField(
            model_name='handwritteninvoice',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2019, 6, 3, 1, 23, 7, 552474, tzinfo=utc), verbose_name='作成日'),
        ),
        migrations.AlterField(
            model_name='invoiceentity',
            name='bank_account_type',
            field=models.CharField(blank=True, choices=[('普通', '普通'), ('当座', '当座')], max_length=100, null=True, verbose_name='口座種類'),
        ),
        migrations.AlterField(
            model_name='invoiceentity',
            name='bank_branch_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='振込支店名'),
        ),
        migrations.AlterField(
            model_name='invoiceentity',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='振込銀行名'),
        ),
        migrations.AlterField(
            model_name='invoiceentity',
            name='credit_card_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='クレカコード'),
        ),
        migrations.AlterField(
            model_name='invoiceentity',
            name='credit_card_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='クレカID'),
        ),
        migrations.AlterField(
            model_name='invoiceentity',
            name='credit_card_settlement_company',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='クレカ決済会社'),
        ),
        migrations.AlterField(
            model_name='invoiceentity',
            name='invoice_address_bld',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='請求住所建物名'),
        ),
        migrations.AlterField(
            model_name='invoiceentity',
            name='invoice_address_city',
            field=models.CharField(max_length=100, verbose_name='請求市区町村'),
        ),
        migrations.AlterField(
            model_name='invoiceentity',
            name='invoice_address_pref',
            field=models.CharField(choices=[('北海道', '北海道'), ('青森県', '青森県'), ('岩手県', '岩手県'), ('宮城県', '宮城県'), ('秋田県', '秋田県'), ('山形県', '山形県'), ('福島県', '福島県'), ('茨城県', '茨城県'), ('栃木県', '栃木県'), ('群馬県', '群馬県'), ('埼玉県', '埼玉県'), ('千葉県', '千葉県'), ('東京都', '東京都'), ('神奈川県', '神奈川県'), ('新潟県', '新潟県'), ('富山県', '富山県'), ('石川県', '石川県'), ('福井県', '福井県'), ('山梨県', '山梨県'), ('長野県', '長野県'), ('岐阜県', '岐阜県'), ('静岡県', '静岡県'), ('愛知県', '愛知県'), ('三重県', '三重県'), ('滋賀県', '滋賀県'), ('京都府', '京都府'), ('大阪府', '大阪府'), ('兵庫県', '兵庫県'), ('奈良県', '奈良県'), ('和歌山県', '和歌山県'), ('鳥取県', '鳥取県'), ('島根県', '島根県'), ('岡山県', '岡山県'), ('広島県', '広島県'), ('山口県', '山口県'), ('徳島県', '徳島県'), ('香川県', '香川県'), ('愛媛県', '愛媛県'), ('高知県', '高知県'), ('福岡県', '福岡県'), ('佐賀県', '佐賀県'), ('長崎県', '長崎県'), ('熊本県', '熊本県'), ('大分県', '大分県'), ('宮崎県', '宮崎県'), ('鹿児島県', '鹿児島県'), ('沖縄県', '沖縄県')], max_length=10, verbose_name='請求都道府県'),
        ),
        migrations.AlterField(
            model_name='invoiceentity',
            name='invoice_address_street',
            field=models.CharField(max_length=100, verbose_name='請求住所番地以降'),
        ),
        migrations.AlterField(
            model_name='invoiceentity',
            name='invoice_closed_at',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='締め日'),
        ),
        migrations.AlterField(
            model_name='invoiceentity',
            name='invoice_period',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='請求周期'),
        ),
        migrations.AlterField(
            model_name='invoiceentity',
            name='invoice_person',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='請求宛名'),
        ),
        migrations.AlterField(
            model_name='invoiceentity',
            name='invoice_project_1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='請求宛名1'),
        ),
        migrations.AlterField(
            model_name='invoiceentity',
            name='invoice_project_2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='請求宛名2'),
        ),
        migrations.AlterField(
            model_name='invoiceentity',
            name='invoice_project_3',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='請求宛名3'),
        ),
        migrations.AlterField(
            model_name='invoiceentity',
            name='invoice_sent_at',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='請求書送付時期'),
        ),
        migrations.AlterField(
            model_name='invoiceentity',
            name='invoice_timing',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='請求タイミング'),
        ),
        migrations.AlterField(
            model_name='invoiceentity',
            name='payment_due_to',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='支払い期日'),
        ),
        migrations.AlterField(
            model_name='invoiceentity',
            name='payment_method',
            field=models.CharField(max_length=100, verbose_name='支払い方法'),
        ),
        migrations.AlterField(
            model_name='invoiceentity',
            name='settlement_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='決済コード'),
        ),
        migrations.AlterField(
            model_name='invoiceentity',
            name='settlement_company',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='決済会社'),
        ),
        migrations.AlterField(
            model_name='invoiceentity',
            name='settlement_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='決済ID'),
        ),
    ]
