# Generated by Django 2.1.5 on 2019-06-03 01:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20190603_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handwritteninvoice',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2019, 6, 3, 1, 29, 42, 497815, tzinfo=utc), verbose_name='作成日'),
        ),
        migrations.AlterField(
            model_name='invoiceentity',
            name='invoice_company_name',
            field=models.CharField(default=1, max_length=100, verbose_name='請求会社名'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoiceentity',
            name='invoice_dept',
            field=models.CharField(default=1, max_length=100, verbose_name='請求部署'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoiceentity',
            name='invoice_person',
            field=models.CharField(default=1, max_length=100, verbose_name='請求宛名'),
            preserve_default=False,
        ),
    ]
