# Generated by Django 2.1.5 on 2019-05-23 11:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20190523_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='handwritteninvoice',
            name='total_tax',
            field=models.IntegerField(default=1, verbose_name='税額合計'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='handwritteninvoice',
            name='total_w_tax',
            field=models.IntegerField(default=1, verbose_name='税込合計'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='handwritteninvoice',
            name='total_wo_tax',
            field=models.IntegerField(default=1, verbose_name='税抜合計'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='handwritteninvoice',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2019, 5, 23, 11, 40, 48, 859908, tzinfo=utc), verbose_name='作成日'),
        ),
    ]
