# Generated by Django 2.1.5 on 2019-06-03 02:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20190603_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='hp_url',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='handwritteninvoice',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2019, 6, 3, 2, 37, 54, 615269, tzinfo=utc), verbose_name='作成日'),
        ),
    ]
