# Generated by Django 2.1.5 on 2019-06-03 03:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20190603_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handwritteninvoice',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2019, 6, 3, 3, 42, 20, 989950, tzinfo=utc), verbose_name='作成日'),
        ),
        migrations.AlterField(
            model_name='invoiceentity',
            name='invoice_dept',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='請求部署'),
        ),
    ]
