# Generated by Django 2.1.5 on 2019-04-23 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_remove_company_company_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='削除フラグ'),
        ),
    ]
