# Generated by Django 2.1.5 on 2019-06-03 12:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20190603_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handwritteninvoice',
            name='address_1',
            field=models.CharField(max_length=50, verbose_name='住所1'),
        ),
        migrations.AlterField(
            model_name='handwritteninvoice',
            name='address_2',
            field=models.CharField(max_length=50, verbose_name='住所2'),
        ),
        migrations.AlterField(
            model_name='handwritteninvoice',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2019, 6, 3, 12, 40, 52, 980709, tzinfo=utc), verbose_name='作成日'),
        ),
    ]
