# Generated by Django 2.1.5 on 2019-06-03 13:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20190603_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handwritteninvoice',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2019, 6, 3, 13, 1, 24, 899317, tzinfo=utc), verbose_name='作成日'),
        ),
        migrations.AlterField(
            model_name='handwritteninvoicedetail',
            name='tax_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
