# Generated by Django 2.1.5 on 2019-04-23 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_company_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceentity',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='削除フラグ'),
        ),
    ]
