# Generated by Django 2.1.5 on 2019-04-23 04:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0009_invoiceentity_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yearmonth', models.CharField(max_length=6, verbose_name='対象月')),
                ('invoice_printed_at', models.DateField(auto_now_add=True, verbose_name='発行日')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('deleted', models.BooleanField(default=False, verbose_name='削除フラグ')),
                ('registered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_registered', to=settings.AUTH_USER_MODEL, verbose_name='登録者')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': '請求書',
                'verbose_name_plural': '請求書',
            },
        ),
        migrations.CreateModel(
            name='InvoiceDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_category_1', models.CharField(max_length=50, verbose_name='商材大区分')),
                ('product_category_2', models.CharField(max_length=50, verbose_name='商材小区分')),
                ('yearmonth', models.CharField(max_length=6, verbose_name='請求月')),
                ('seq_number', models.CharField(max_length=50, verbose_name='SEQNO')),
                ('order_number', models.CharField(max_length=50, verbose_name='申込管理番号')),
                ('service_start_date', models.DateField(verbose_name='サービス開始日')),
                ('service_name', models.CharField(max_length=50, verbose_name='請求明細内容')),
                ('invoice_amount_wo_tax', models.IntegerField(verbose_name='請求金額(税抜)')),
                ('tax_type', models.CharField(choices=[('課税', '課税'), ('非課税', '非課税')], max_length=10, verbose_name='税区分')),
                ('tax_rate_perc', models.IntegerField(verbose_name='税率')),
                ('tax_amount', models.IntegerField(verbose_name='請求金額(税額)')),
                ('invoice_amount_w_tax', models.IntegerField(verbose_name='請求金額(税込)')),
                ('note', models.TextField(blank=True, null=True, verbose_name='備考')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('deleted', models.BooleanField(default=False, verbose_name='削除フラグ')),
                ('invoice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.Invoice', verbose_name='請求書')),
            ],
            options={
                'verbose_name': '請求明細',
                'verbose_name_plural': '請求明細',
            },
        ),
        migrations.AlterField(
            model_name='company',
            name='address_pref',
            field=models.CharField(choices=[('東京都', '東京都'), ('北海道', '北海道'), ('秋田県', '秋田県')], max_length=10, verbose_name='契約者都道府県'),
        ),
        migrations.AlterField(
            model_name='invoiceentity',
            name='bank_account_type',
            field=models.CharField(choices=[('普通', '普通'), ('当座', '当座')], max_length=20, verbose_name='口座種類'),
        ),
        migrations.AlterField(
            model_name='invoiceentity',
            name='bank_branch_name',
            field=models.CharField(max_length=20, verbose_name='振込支店名'),
        ),
        migrations.AlterField(
            model_name='invoiceentity',
            name='invoice_address_pref',
            field=models.CharField(choices=[('東京都', '東京都'), ('北海道', '北海道'), ('秋田県', '秋田県')], max_length=10, verbose_name='請求都道府県'),
        ),
        migrations.AlterField(
            model_name='invoiceentity',
            name='invoice_address_street',
            field=models.CharField(max_length=50, verbose_name='請求住所番地以降'),
        ),
        migrations.AlterField(
            model_name='invoiceentity',
            name='invoice_sent_at',
            field=models.CharField(choices=[('末日', '末日'), ('20日', '20日')], max_length=20, verbose_name='請求書送付時期'),
        ),
        migrations.AlterField(
            model_name='invoiceentity',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='特記事項'),
        ),
        migrations.AddField(
            model_name='invoicedetail',
            name='invoice_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.InvoiceEntity', verbose_name='請求管理簿'),
        ),
        migrations.AddField(
            model_name='invoicedetail',
            name='registered_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detail_registered', to=settings.AUTH_USER_MODEL, verbose_name='登録者'),
        ),
        migrations.AddField(
            model_name='invoicedetail',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detail_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新者'),
        ),
    ]
