# Generated by Django 2.1 on 2019-06-04 13:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_auto_20190603_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handwritteninvoice',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2019, 6, 4, 13, 38, 15, 388612, tzinfo=utc), verbose_name='作成日'),
        ),
    ]
