# Generated by Django 2.1.5 on 2019-04-23 06:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0010_auto_20190423_1330'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[(1, '会社情報'), (2, '請求管理簿'), (3, '請求明細')], max_length=10, verbose_name='ファイル種類')),
                ('csv_file', models.FileField(upload_to='company_csv', validators=[django.core.validators.FileExtensionValidator(['csv'])], verbose_name='アップロードファイル')),
                ('processed_at', models.DateTimeField(auto_now_add=True, verbose_name='処理日')),
                ('record_count', models.IntegerField(verbose_name='件数')),
                ('error_count', models.IntegerField(verbose_name='エラー件数')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='実行ユーザ')),
            ],
            options={
                'verbose_name': 'アップロード',
                'verbose_name_plural': 'アップロードファイル',
                'ordering': ['pk'],
            },
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['pk'], 'verbose_name': '会社', 'verbose_name_plural': '会社'},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['pk'], 'verbose_name': '請求書', 'verbose_name_plural': '請求書'},
        ),
        migrations.AlterModelOptions(
            name='invoicedetail',
            options={'ordering': ['pk'], 'verbose_name': '請求明細', 'verbose_name_plural': '請求明細'},
        ),
        migrations.AlterModelOptions(
            name='invoiceentity',
            options={'ordering': ['pk'], 'verbose_name': '請求管理簿', 'verbose_name_plural': '請求管理簿'},
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='yearmonth',
        ),
        migrations.AlterField(
            model_name='invoicedetail',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='details', to='web.Invoice', verbose_name='請求書'),
        ),
        migrations.AlterField(
            model_name='invoicedetail',
            name='invoice_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_invoice_details', to='web.InvoiceEntity', verbose_name='請求管理簿'),
        ),
    ]
