# Generated by Django 2.1.5 on 2019-04-23 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_auto_20190423_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_entity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='my_invoice', to='web.InvoiceEntity', verbose_name='請求管理簿'),
            preserve_default=False,
        ),
    ]
