# Generated by Django 2.1.5 on 2019-04-25 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_invoice_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='invoice_entity',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='yearmonth',
        ),
        migrations.RemoveField(
            model_name='invoicedetail',
            name='invoice_amount_w_tax',
        ),
    ]
