# Generated by Django 2.1.5 on 2019-04-25 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_auto_20190425_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='id',
        ),
        migrations.RemoveField(
            model_name='invoicedetail',
            name='invoice',
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_id',
            field=models.CharField(default=1, max_length=50, primary_key=True, serialize=False, verbose_name='請求書ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoicedetail',
            name='invoice_id',
            field=models.CharField(default=1, max_length=50, verbose_name='請求書ID'),
            preserve_default=False,
        ),
    ]
